app/core/urls.py
from app.core.views import brand, category, company, customer, iva, line, supplier, product, paymentMethod, price, \
  statistics
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path

app_name = 'core'
urlpatterns = [

                # URLs de marcas
                path('brands_list/', brand.BrandListView.as_view(), name='brand_list'),
                path('brands_create/', brand.BrandCreateView.as_view(), name='brand_create'),
                path('brands_update/<int:pk>/', brand.BrandUpdateView.as_view(), name='brand_update'),
                path('brands_delete/<int:pk>/', brand.BrandDeleteView.as_view(), name='brand_delete'),
                path('brand-suggestions/', brand.BrandSuggestionsView.as_view(), name='brand_suggestions'),

                # URLs de categorías
                path('category_list/', category.CategoryListView.as_view(), name='category_list'),
                path('category_create/', category.CategoryCreateView.as_view(), name='category_create'),
                path('category_update/<int:pk>/', category.CategoryUpdateView.as_view(), name='category_update'),
                path('category_delete/<int:pk>/', category.CategoryDeleteView.as_view(), name='category_delete'),
                path('category-suggestions/', category.CategorySuggestionsView.as_view(), name='category_suggestions'),

                # URLs de empresa
                path('company_list/', company.CompanyListView.as_view(), name='company_list'),
                path('company_create/', company.CompanyCreateView.as_view(), name='company_create'),
                path('company_update/<int:pk>/', company.CompanyUpdateView.as_view(), name='company_update'),
                path('company_delete/<int:pk>/', company.CompanyDeleteView.as_view(), name='company_delete'),
                path('company-suggestions/', company.CompanySuggestionsView.as_view(), name='company_suggestions'),

                # URLs de clientes
                path('customer_list/', customer.CustomerListView.as_view(), name='customer_list'),
                path('customer_create/', customer.CustomerCreateView.as_view(), name='customer_create'),
                path('customer_update/<int:pk>/', customer.CustomerUpdateView.as_view(), name='customer_update'),
                path('customer_delete/<int:pk>/', customer.CustomerDeleteView.as_view(), name='customer_delete'),
                path('customer-suggestions/', customer.CustomerSuggestionsView.as_view(), name='customer_suggestions'),

                # URLs de iva
                path('iva_list/', iva.IvaListView.as_view(), name='iva_list'),
                path('iva_create/', iva.IvaCreateView.as_view(), name='iva_create'),
                path('iva_update/<int:pk>/', iva.IvaUpdateView.as_view(), name='iva_update'),
                path('iva_delete/<int:pk>/', iva.IvaDeleteView.as_view(), name='iva_delete'),
                path('iva-suggestions/', iva.IvaSuggestionsView.as_view(), name='iva_suggestions'),

                # URLs de línea
                path('lines_list/', line.LineListView.as_view(), name='line_list'),
                path('lines_create/', line.LineCreateView.as_view(), name='line_create'),
                path('lines_update/<int:pk>/', line.LineUpdateView.as_view(), name='line_update'),
                path('lines_delete/<int:pk>/', line.LineDeleteView.as_view(), name='line_delete'),
                path('lines-suggestions/', line.LineSuggestionsView.as_view(), name='line_suggestions'),

                # URLs de metodo de pago
                path('paymentMethod_list/', paymentMethod.PaymentMethodListView.as_view(), name='paymentMethod_list'),
                path('paymentMethod_create/', paymentMethod.PaymentMethodCreateView.as_view(),
                     name='paymentMethod_create'),
                path('paymentMethod_update/<int:pk>/', paymentMethod.PaymentMethodUpdateView.as_view(),
                     name='paymentMethod_update'),
                path('paymentMethod_delete/<int:pk>/', paymentMethod.PaymentMethodDeleteView.as_view(),
                     name='paymentMethod_delete'),
                path('paymentMethod-suggestions/', paymentMethod.PaymentMethodSuggestionsView.as_view(),
                     name='paymentMethod_suggestions'),

                # URLS de precios
                path("price_list/", price.ProductPriceListView.as_view(), name="price_list"),
                path("price_create/", price.ProductPriceCreateView.as_view(), name="price_create"),
                path("price_update/<int:pk>/", price.ProductPriceUpdateView.as_view(), name="price_update"),
                path("price_delete/<int:pk>/", price.ProductPriceDeleteView.as_view(), name="price_delete"),
                path('price-suggestions/', price.ProductPriceSuggestionsView.as_view(), name='price_suggestions'),

                # URLs de productos
                path('product_list/', product.ProductListView.as_view(), name='product_list'),
                path('product_create/', product.ProductCreateView.as_view(), name='product_create'),
                path('product_update/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
                path('product_delete/<int:pk>/', product.ProductDeleteView.as_view(), name='product_delete'),
                path('product-suggestions/', product.ProductSuggestionsView.as_view(), name='product_suggestions'),

                # URLs de proveedores
                path('supplier_list/', supplier.SupplierListView.as_view(), name='supplier_list'),
                path('supplier_create/', supplier.SupplierCreateView.as_view(), name='supplier_create'),
                path('supplier_update/<int:pk>/', supplier.SupplierUpdateView.as_view(), name='supplier_update'),
                path('supplier_delete/<int:pk>/', supplier.SupplierDeleteView.as_view(), name='supplier_delete'),
                path('supplier-suggestions/', supplier.SupplierSuggestionsView.as_view(), name='supplier_suggestions'),

                # URLs de estadisticas
                path('sales_data/', statistics.sales_data, name='sales_data'),
                path('purchases_data/', statistics.purchases_data, name='purchases_data'),
                path('statistics_list/', statistics.StatisticsListView.as_view(), name='statistics'),
                path('invoice_details/', statistics.invoice_details, name='invoice_details'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proy_sales/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app.core.views.home import HomeTemplateView
from app.security.views.modulos import ModuloTemplateView

urlpatterns = [
                path('admin/', admin.site.urls),
                path('', HomeTemplateView.as_view(), name='home'),
                path('modulos/', ModuloTemplateView.as_view(), name='modulos'),
                path('security/', include('app.security.urls', namespace='security')),
                path('core/', include('app.core.urls', namespace='core')),
                path('sales/', include('app.sales.urls', namespace='sales')),
                path('purcharse/', include('app.purcharse.urls', namespace='purchase')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/forms/brand.py
from django.forms import ModelForm, ImageField, FileInput
from app.core.models import Brand
from django.utils import timezone
from django import forms
import datetime


class BrandForm(ModelForm):
  image = forms.ImageField(required=False, label="Foto de Marca", widget=FileInput(attrs={
    "class": "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light",
  }))

  class Meta:
    model = Brand
    fields = ["description", "active", "image"]
    labels = {
      "description": "Descripción ",
      "state": "Estado",
      "image": "Imagen",
    }
    error_messages = {
      "description": {
        "unique": "Ya existe una marca con este nombre.",
      },
    }
    widgets = {
      "description": forms.TextInput(attrs={
        "placeholder": "Ingrese descripción del producto",
        "id": "id_description",
        "class": "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 pr-12 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light",
      }),
      "state": forms.CheckboxInput(attrs={
        "class": "mt-1 block px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
      }),
    }

  def clean_description(self):
    description = self.cleaned_data.get("description")
    return description.upper()

app/core/views/brand.py
from app.security.mixins.mixins import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from app.core.forms.brand import BrandForm
from app.core.models import Brand
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import JsonResponse


# vista para el buscadador dinamico
class BrandSuggestionsView(ListView):
  def get(self, request, *args, **kwargs):
    term = request.GET.get('term', '')
    suggestions = Brand.objects.filter(description__icontains=term).values('description', 'active')[
                  :10]
    suggestions_list = list(suggestions)
    return JsonResponse(suggestions_list, safe=False)


class BrandListView(PermissionMixin, ListViewMixin, ListView):
  model = Brand
  template_name = 'core/brands/list.html'
  context_object_name = 'brands'
  permission_required = 'view_brand'

  def get_queryset(self):
    q1 = self.request.GET.get('q')
    if q1:
      query = Q(description__icontains=q1)
    else:
      query = Q(active=True)

    return self.model.objects.filter(query).order_by('id')


class BrandCreateView(PermissionMixin, CreateViewMixin, CreateView):
  model = Brand
  form_class = BrandForm
  template_name = 'core/brands/form.html'
  success_url = reverse_lazy('core:brand_list')
  permission_required = 'add_brand'

  def form_valid(self, form):
    response = super().form_valid(form)
    brand = self.object
    messages.success(self.request, f"Éxito al crear la marca {brand.description}.")
    return response


class BrandUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
  model = Brand
  form_class = BrandForm
  template_name = 'core/brands/form.html'
  success_url = reverse_lazy('core:brand_list')
  permission_required = 'change_brand'

  def form_valid(self, form):
    response = super().form_valid(form)
    brand = self.object
    messages.success(self.request, f"Éxito al actualizar la marca {brand.description}.")
    return response


class BrandDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
  model = Brand
  template_name = 'core/delete.html'
  success_url = reverse_lazy('core:brand_list')
  permission_required = 'delete_brand'

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.object = None

  def delete(self, request, *args, **kwargs):
    self.object = self.get_object()
    success_message = f"Éxito al eliminar la marca {self.object.description}."
    self.object.delete()
    messages.success(self.request, success_message)
    return super().delete(request, *args, **kwargs)

app/core/views/category.py
from app.security.mixins.mixins import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from app.core.forms.category import CategoryForm
from app.core.models import Category
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q
from django.http import JsonResponse


# vista para el buscadador dinamico
class CategorySuggestionsView(ListView):
  def get(self, request, *args, **kwargs):
    term = request.GET.get('term', '')
    suggestions = Category.objects.filter(description__icontains=term).values('description', 'active')[
                  :10]
    suggestions_list = list(suggestions)
    return JsonResponse(suggestions_list, safe=False)


class CategoryListView(PermissionMixin, ListViewMixin, ListView):
  model = Category
  template_name = 'core/categories/list.html'
  context_object_name = 'category'
  permission_required = 'view_category'

  def get_queryset(self):
    q1 = self.request.GET.get('q')
    if q1:
      query = Q(description__icontains=q1)
    else:
      query = Q(active=True)

    return self.model.objects.filter(query).order_by('id')


class CategoryCreateView(PermissionMixin, CreateViewMixin, CreateView):
  model = Category
  form_class = CategoryForm
  template_name = 'core/categories/form.html'
  success_url = reverse_lazy('core:category_list')
  permission_required = 'add_category'

  def form_valid(self, form):
    response = super().form_valid(form)
    category = self.object
    messages.success(self.request, f"Éxito al crear la categoría {category.description}.")
    return response


class CategoryUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
  model = Category
  form_class = CategoryForm
  template_name = 'core/categories/form.html'
  success_url = reverse_lazy('core:category_list')
  permission_required = 'change_category'

  def form_valid(self, form):
    response = super().form_valid(form)
    category = self.object
    messages.success(self.request, f"Éxito al actualizar la categoría {category.description}.")
    return response


class CategoryDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
  model = Category
  template_name = 'core/delete.html'
  success_url = reverse_lazy('core:category_list')
  permission_required = 'delete_category'

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.object = None

  def delete(self, request, *args, **kwargs):
    self.object = self.get_object()
    success_message = f"Éxito al eliminar la categoría {self.object.description}."
    self.object.delete()
    messages.success(self.request, success_message)
    return super().delete(request, *args, **kwargs)

app/core/views/home.py
from app.security.instance.menu_module import MenuModule
from app.security.mixins.mixins import PermissionMixin
from django.views.generic import TemplateView


class HomeTemplateView(TemplateView):
  template_name = 'components/home.html'

  def get_context_data(self, **kwargs):
    # context = super().get_context_data(**kwargs)
    context = {"title1": "IC - Inicio",
               "title2": "Corporacion el Rosado"}

    return context

app/core/views/iva.py
from app.security.mixins.mixins import CreateViewMixin, DeleteViewMixin, ListViewMixin, PermissionMixin, UpdateViewMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from app.core.forms.iva import IvaForm
from app.core.models import Iva
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import render
from django.http import JsonResponse
from folium.plugins import FastMarkerCluster
import folium


# vista para el buscadador dinamico
class IvaSuggestionsView(ListView):
  def get(self, request, *args, **kwargs):
    term = request.GET.get('term', '')
    suggestions = Iva.objects.filter(
      Q(description__icontains=term) | Q(value__icontains=term)
    ).values('description', 'value', 'active')[:10]
    suggestions_list = list(suggestions)
    return JsonResponse(suggestions_list, safe=False)


class IvaListView(PermissionMixin, ListViewMixin, ListView):
  model = Iva
  template_name = 'core/ivas/list.html'
  context_object_name = 'iva'
  permission_required = 'view_iva'

  def get_queryset(self):
    q1 = self.request.GET.get('q')
    if q1:
      query = Q(description__icontains=q1)
    else:
      query = Q(active=True)

    return self.model.objects.filter(query).order_by('id')


class IvaCreateView(PermissionMixin, CreateViewMixin, CreateView):
  model = Iva
  form_class = IvaForm
  template_name = 'core/ivas/form.html'
  success_url = reverse_lazy('core:iva_list')
  permission_required = 'add_iva'

  def form_valid(self, form):
    response = super().form_valid(form)
    iva = self.object
    messages.success(self.request, f"Éxito al crear la Iva {iva.description}.")
    return response


class IvaUpdateView(PermissionMixin, UpdateViewMixin, UpdateView):
  model = Iva
  form_class = IvaForm
  template_name = 'core/ivas/form.html'
  success_url = reverse_lazy('core:iva_list')
  permission_required = 'change_iva'

  def form_valid(self, form):
    response = super().form_valid(form)
    iva = self.object
    messages.success(self.request, f"Éxito al actualizar la marca {iva.description}.")
    return response


class IvaDeleteView(PermissionMixin, DeleteViewMixin, DeleteView):
  model = Iva
  template_name = 'core/delete.html'
  success_url = reverse_lazy('core:iva_list')
  permission_required = 'delete_iva'

  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.object = None

  def delete(self, request, *args, **kwargs):
    self.object = self.get_object()
    success_message = f"Éxito al eliminar el Iva {self.object.description}."
    self.object.delete()
    messages.success(self.request, success_message)
    return super().delete(request, *args, **kwargs)

templates/core/products/list.html
{% extends 'components/base.html' %}
{% block content %}
    {% load static %}
    <title>{% block title %} {{ title1 }} {% endblock title %}</title>
    <section class="dark:bg-principal">
        <div class="text-center" data-aos="fade-up" data-aos-delay="200">

            <!-- Cabecera -->
            <div class="sm:pt-28 lg:pt-24">
                <div class="flex flex-col items-center justify-center">
                    <span class="rounded-full bg-indigo-500 px-2 py-1 text-white uppercase text-sm">
                        {{ title1 }}
                    </span>
                </div>
                <h1 class="dark:text-white text-4xl text-center mt-6 font-Pacifico">
                    {{ title2 }}
                </h1>
            </div>

            <!-- Barra de búsqueda -->
            <div class="p-4 flex justify-center">
                <label for="table-search" class="sr-only">Search</label>
                <div class="relative mt-1">
                    <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true"
                             xmlns="http://www.w3.org/2000/svg"
                             fill="none" viewBox="0 0 20 20">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                  d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"></path>
                        </svg>
                    </div>
                    <form method="GET" action="{% url 'core:product_list' %}">
                        <input type="text" name="q" id="table-search"
                               class="text-center pl-10 shadow-sm bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 pr-12 dark:bg-principal dark:border-gray-600 dark:placeholder-gray-400 dark:text-gray-400 dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light"
                               placeholder="Buscar" value="{{ request.GET.q }}" autocomplete="off">
                    </form>
                </div>
            </div>

            <!-- Contenedor de sugerencias -->
            <div id="suggestions-container" style="background-color: #050812; border: 3px solid #2D64BD; color :#7D838F"
                 class="absolute left-1/2 transform -translate-x-1/2 mt-2 z-10 bg-white border border-gray-300 text-gray-900 rounded-lg shadow-lg max-h-80 overflow-y-auto">
            </div>
        </div>

        <!-- Tabla -->
            <div class="overflow-x-auto">
                <table class="w-full text-center text-lg">
                    <thead class="uppercase font-Tiny5 bg-gray-50 dark:bg-secundario dark:text-blue-300">
                    <tr>
                        <th scope="col" class="px-6 py-3">ID</th>
                        <th scope="col" class="px-6 py-3">Imagen</th>
                        <th scope="col" class="px-6 py-3">Producto</th>
                        <th scope="col" class="px-6 py-3">Fecha Exp.</th>
                        <th scope="col" class="px-6 py-3">Creacion</th>
                        <th scope="col" class="px-6 py-3">Actualización</th>
                        <th scope="col" class="px-6 py-3">Marca</th>
                        <th scope="col" class="px-6 py-3">Linea</th>
                        <th scope="col" class="px-6 py-3">Categoría</th>
                        <th scope="col" class="px-6 py-3">Precio</th>
                        <th scope="col" class="px-6 py-3">Costo</th>
                        <th scope="col" class="px-6 py-3">Stock</th>
                        <th scope="col" class="px-6 py-3">Iva</th>
                        <th scope="col" class="px-6 py-3">Estado</th>
                        <th scope="col" class="px-6 py-3">Activo</th>
                        <th scope="col" class="px-6 py-3">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in products %}
                        <tr class="dark:text-gray-400 bg-white border-b dark:bg-[#0b1121] dark:border-secundario hover:bg-gray-50 dark:hover:bg-[#121c33]">
                            <td class="w-4 p-4">{{ item.id }}</td>

                            <th><img class="mx-auto w-16 h-16 object-contain rounded-2xl"
                                     src="{% if item.image %}{{ item.image.url }}{% else %}{% static 'img/default_product.jpg' %}{% endif %}"
                                     alt="Imagen del producto">
                            </th>

                            <td class="px-2 py-4">{{ item.description }}</td>
                            <td class="px-2 py-4">{{ item.expiration_date  |  date:"Y-m-d" }}</td>
                            <td class="px-2 py-4">{{ item.created  |  date:"Y-m-d  H:i" }}</td>
                            <td class="px-2 py-4">{{ item.updated  |  date:"Y-m-d  -|-  H:i" }}</td>
                            <td class="px-2 py-4">{{ item.brand }}</td>
                            <td class="px-2 py-4">{{ item.line }}</td>
                            <td class="px-2 py-4">{{ item.get_categories }}</td>

                            <td class="px-2 py-4 text-green-600 dark:text-green-300 font-black">
                                $ {{ item.price }}
                            </td>

                            <td class="px-2 py-4 text-green-600 dark:text-green-300 font-black">
                                $ {{ item.cost }}
                            </td>

                            <td class="px-2 py-4">{{ item.stock }}</td>
                            <td class="px-2 py-4">{{ item.iva }}</td>
                            <td class="px-2 py-4">{{ item.state }}</td>

                            <td class="px-6 py-4">
                                {% if item.active %}
                                    <i class="fa-solid fa-check text-green-500"></i>
                                {% else %}
                                    <i class="fa-solid fa-square-minus text-red-500"></i>
                                {% endif %}
                            </td>

                            <td class="px-6 py-4 text-2xl">
                                {% if permissions.change_product %}
                                <a href="{% url 'core:product_update' item.id %}"
                                   class="text-blue-600 dark:text-blue-500">
                                    <i class="ri-edit-fill"></i>
                                </a>
                                {% endif %}

                                {% if permissions.delete_product %}
                                    <button class="text-red-600 dark:text-red-500 ml-2"
                                            onclick="openDeleteModal('{{ item.id }}', '{{ item.description }}' )">
                                        <i class="fa-solid fa-trash"></i>
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <!-- Paginación -->
        <div class="flex justify-center mt-4">
            <nav aria-label="Page navigation example">
                <ul class="inline-flex -space-x-px">

                    {% if page_obj.has_previous %}
                        <li>
                            <a href="?page=1"
                               class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Anterior</a>
                        </li>
                    {% endif %}

                    {% for num in page_obj.paginator.page_range %}
                        <li>
                            <a href="?page={{ num }}"
                               class="flex items-center justify-center px-3 h-8 leading-tight {% if num == page_obj.number %}text-blue-600 bg-blue-50 border border-gray-300 hover:bg-blue-100 hover:text-blue-700 dark:bg-secundario dark:border-principal dark:text-blue-300{% else %}text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white{% endif %}">
                                {{ num }}
                            </a>
                        </li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li>
                            <a href="?page={{ page_obj.next_page_number }}"
                               class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-[#0b1121] dark:border-secundario dark:text-gray-400 dark:hover:bg-[#121c33] dark:hover:text-white">Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>

        <!-- Btn agg o ir a casa -->
        <div>
            <div class="flex flex-col md:flex-row justify-center form-group text-center p-4">
                {% if permissions.add_product %}
                    <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full mr-0 md:mr-2 mb-2 md:mb-0 flex items-center justify-center"
                       href="{% url 'core:product_create' %}">
                        <i class="fa-solid fa-plus mr-2"></i> Nuevo producto
                    </a>
                {% endif %}
                <a class="bg-blue-700 hover:bg-blue-800 text-white py-2 px-4 rounded-full flex items-center justify-center"
                   href="{% url 'modulos' %}">
                    <i class="fa-solid fa-house"></i>
                </a>
            </div>
        </div>
    </section>
    
      {#    script buscador dinamico #}
    <script>
        const searchInput = document.getElementById('table-search');
        const suggestionsContainer = document.getElementById('suggestions-container');
        const tableRows = document.querySelectorAll('#supplier-table tbody tr');

        searchInput.addEventListener('input', function () {
            const searchTerm = this.value.trim();

            if (searchTerm === '') {
                showAllRows();
                suggestionsContainer.innerHTML = '';
                suggestionsContainer.style.display = 'none';
                return;
            }
            fetchSuggestions(searchTerm);
        });

        function fetchSuggestions(searchTerm) {
            fetch(`/core/product-suggestions/?term=${encodeURIComponent(searchTerm)}`)
                .then(response => response.json())
                .then(data => {
                    const suggestionsHTML = data.map(item => {
                        const activeStatus = item.active ? '<i class="fa-solid fa-check text-green-500"></i>' : '<i class="fa-solid fa-square-minus text-red-500"></i>';
                        return `<div class="suggestion-item" style="cursor: pointer; padding: 5px" data-description="${item.description}">${item.description}   -   ${item.stock}  -  ${activeStatus}</div>`;
                    }).join('');
                    suggestionsContainer.innerHTML = suggestionsHTML;
                    suggestionsContainer.style.display = 'block';
                })
                .catch(error => {
                    console.error('Error al buscar sugerencias de marca:', error);
                    suggestionsContainer.innerHTML = '<div>Error al buscar sugerencias de marca.</div>';
                    suggestionsContainer.style.display = 'block';
                });
        }

        function showAllRows() {
            tableRows.forEach(row => {
                row.style.display = 'table-row';
            });
        }

        document.addEventListener('click', function (event) {
            if (!suggestionsContainer.contains(event.target) && event.target !== searchInput) {
                suggestionsContainer.style.display = 'none';
            }
        });

        suggestionsContainer.addEventListener('click', function (event) {
            if (event.target.classList.contains('suggestion-item')) {
                const description = event.target.getAttribute('data-description');

                searchInput.value = description;

                let found = false;
                tableRows.forEach(row => {
                    const rowData = row.textContent.trim();
                    if (rowData.includes(description)) {
                        row.style.display = 'table-row';
                        found = true;
                    } else {
                        row.style.display = 'none';
                    }
                });

                if (!found) {
                    showAllRows();
                }

                suggestionsContainer.style.display = 'none';

                searchInput.form.submit();
            }
        });
    </script>

    {% include 'fragments/delete.html' %}

    <script>
        function openDeleteModal(id, description) {
            const deleteForm = document.getElementById('deleteForm');
            deleteForm.action = `{% url 'core:product_delete' 0 %}`.replace('0', id);
            document.getElementById('Description').textContent = `ID: ${id} - ${description}`;
            document.getElementById('deleteModal').classList.remove('hidden');
        }

        function closeModal() {
            document.getElementById('deleteModal').classList.add('hidden');
        }
    </script>

{% endblock %}